# Generated by Django 4.1.3 on 2022-12-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0002_rename_name_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reminder',
            field=models.BooleanField(default=False),
        ),
    ]
